# -*- coding: utf-8 -*-
"""app_portafolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Fi54j99BIKJSmiP-OfE3ugBjFMb3wwi
"""



# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

#Importamos las librerias
import streamlit as st
import pandas as pd

st.title("Mi primera aplicación en Stremlit :) ")